In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
ds = pd.read_csv('mushrooms.csv')
ds.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
le = LabelEncoder()
df = ds.apply(le.fit_transform)
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color   ...     stalk-surface-below-ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [4]:
data = df.values
data = np.array(data)
np.random.shuffle(data)
print data

[[0 5 3 ... 3 4 0]
 [1 2 2 ... 7 4 0]
 [1 2 3 ... 1 5 1]
 ...
 [1 2 3 ... 1 4 1]
 [0 5 2 ... 3 1 2]
 [0 5 3 ... 2 5 1]]


In [5]:
x = data[:200,1:]
y = data[:200,0]
y[y==0]=-1
print(x.shape)
print(y.shape)


(200, 22)
(200,)


In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [7]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 22)
(40, 22)
(160,)
(40,)


In [8]:
def hypo(x,w,b):
    return np.dot(w,x.T)+b



In [9]:
def hingeloss(w,b,x,y):
    loss = 0
    loss+=0.5*np.dot(w,w.T)
    
    ti = np.multiply(y,hypo(x,w,b))
    
    ##Eliminating the ON Street points
    ##Allowing Some Error Points
    ti = ti-1
    ti=ti[ti>0]
        
    loss+=np.sum(ti)
    
    return loss


In [10]:
def fit(x,y,lr=0.001,n_epochs=500):
    n_features=x.shape[1]
    n_samples = x.shape[0]
    
    w = np.random.random((n_features,))
    b = 0.0
    c = 1.0
    losses = []
    
    for epoch in range(n_epochs):
        loss = hingeloss(w,b,x,y)
        losses.append(loss)
        
        gradb=0.0
        gradw = np.zeros((n_features,))
        
        ti = np.multiply(y,hypo(x,w,b))
        for ix in range(n_features):
            for iy in range(ti.shape[0]):
                if ti[iy]>1:
                    gradw[ix]+=0
                    gradb+=0
                    
                else:
                    gradw[ix]+=c*x[iy][ix]*y[iy]
                    gradb+=c*y[iy]
        w = w -lr*w + lr*gradw
        b = b + lr*gradb
    return w,b

    

In [15]:
def acccuracy(x,y,w_fit,b_fit):
    hx = hypo(x,w_fit,b_fit)
    hx[hx>=0]=1
    hx[hx<0]=-1
    print(b_fit)
#     print(hx.shape[0])
    return float(hx[hx==y].shape[0])/y.shape[0]
#     return 0


## Fitting and Testing

In [12]:
w_fit,b_fit = fit(x_train,y_train)


In [16]:
print(acccuracy(x_test,y_test,w_fit,b_fit))

3.982
0.9
